"""
reports/modules/example_module.py — Minimal infrastructure test module.

This module exists solely to verify that the module infrastructure works
end-to-end: registration, discovery, compute(), all three renderers, and
audit documentation.

Do not use this module in production delivery groups.

To test in isolation::

    python -c "
    from reports.modules import registry
    mod = registry.get('example')()
    print(mod.get_audit_info())
    "
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

import pandas as pd

from reports.modules.base import BaseModule, ModuleConfig, ModuleData
from reports.modules.registry import register_module

logger = logging.getLogger(__name__)


@register_module
class ExampleModule(BaseModule):
    """
    Minimal module for testing the module infrastructure.

    Counts rows in ``vulns_df`` and renders that count in all three
    output formats (PDF, Excel, email).  No real metric logic.

    Supported options
    -----------------
    None — this module accepts no options.
    """

    MODULE_ID         = "example"
    DISPLAY_NAME      = "Example Module (Infrastructure Test)"
    DESCRIPTION       = ("Minimal module for testing the module infrastructure. "
                         "Not for production use.")
    REQUIRED_DATA     = ["vulns"]
    SUPPORTED_OUTPUTS = ["pdf", "excel", "email"]
    VERSION           = "1.0.0"

    # ------------------------------------------------------------------
    # compute
    # ------------------------------------------------------------------

    def compute(
        self,
        vulns_df:    pd.DataFrame,
        assets_df:   pd.DataFrame,
        report_date: Any,
        config:      ModuleConfig,
        **kwargs:    Any,
    ) -> ModuleData:
        """
        Count total rows in ``vulns_df`` and return as a single metric.

        Always succeeds unless an unexpected exception occurs, in which
        case ``ModuleData.error`` is set and all data fields are empty.
        """
        logger.debug(
            "%s compute() called — vulns_df rows: %d, assets_df rows: %d",
            self._log_prefix(), len(vulns_df), len(assets_df),
        )

        try:
            total = len(vulns_df)

            return ModuleData(
                module_id    = self.MODULE_ID,
                display_name = self.DISPLAY_NAME,
                metrics      = {"Total Findings": total},
                table_data   = [],
                chart_data   = {},
                summary_text = (
                    f"Example module found {total:,} total findings."
                ),
                metadata     = {
                    "computed_at":     str(report_date),
                    "vulns_row_count": total,
                    "assets_row_count": len(assets_df),
                },
                error        = None,
            )

        except Exception as exc:  # noqa: BLE001
            logger.error(
                "%s compute() failed: %s", self._log_prefix(), exc,
                exc_info=True,
            )
            return self._empty_result(str(exc), config)

    # ------------------------------------------------------------------
    # render_pdf_section
    # ------------------------------------------------------------------

    def render_pdf_section(
        self,
        data:   ModuleData,
        config: ModuleConfig,
    ) -> str:
        """
        Render a minimal HTML section showing the total finding count.

        Returns an error callout if ``data.error`` is set.
        """
        if "pdf" not in self.SUPPORTED_OUTPUTS:
            return ""

        if data.error:
            return (
                f'<div class="error-box">'
                f"<strong>{self.DISPLAY_NAME}</strong>: {data.error}"
                f"</div>"
            )

        total = data.metrics.get("Total Findings", 0)

        return f"""
<div class="module-section">
  <h2 class="section-heading">{data.display_name}</h2>
  <p class="explanatory-text">{data.summary_text}</p>
  <div class="kpi-row">
    <div class="kpi-tile">
      <span class="kpi-value">{total:,}</span>
      <span class="kpi-label">Total Findings</span>
    </div>
  </div>
  <p class="explanatory-text" style="color:#888;font-size:7.5pt;">
    This section is generated by the example infrastructure-test module
    and should not appear in production reports.
  </p>
</div>"""

    # ------------------------------------------------------------------
    # render_excel_tabs
    # ------------------------------------------------------------------

    def render_excel_tabs(
        self,
        data:     ModuleData,
        workbook: Any,
        config:   ModuleConfig,
    ) -> list[str]:
        """
        Write a single "Example" tab with the total finding count.

        Returns ``[]`` if Excel output is not supported.
        Writes an error row if ``data.error`` is set.
        """
        if "excel" not in self.SUPPORTED_OUTPUTS:
            return []

        tab_name = "Example"

        try:
            ws = workbook.create_sheet(tab_name)

            if data.error:
                ws["A1"] = "Error"
                ws["B1"] = data.error
                return [tab_name]

            ws["A1"] = "Metric"
            ws["B1"] = "Value"
            ws["A2"] = "Total Findings"
            ws["B2"] = data.metrics.get("Total Findings", 0)
            ws["A3"] = "Computed At"
            ws["B3"] = data.metadata.get("computed_at", "")

            return [tab_name]

        except Exception as exc:  # noqa: BLE001
            logger.error(
                "%s render_excel_tabs() failed: %s",
                self._log_prefix(), exc, exc_info=True,
            )
            return []

    # ------------------------------------------------------------------
    # get_audit_info
    # ------------------------------------------------------------------

    def get_audit_info(self) -> dict:
        """
        Return calculation documentation for audit and runbook records.
        """
        return {
            **super().get_audit_info(),
            "calculations": {
                "Total Findings": (
                    "len(vulns_df) — count of all rows in the vulnerability "
                    "DataFrame after tag and severity filtering has been "
                    "applied by the caller. No additional filters are "
                    "applied inside this module."
                ),
            },
        }
